#!/usr/bin/env ruby

require 'csv'
require 'dotenv'
require 'pony'
require_relative 'lib/msg'
require_relative 'lib/email'

Dotenv.load

csv_file = ENV['CSV'] || 'test.csv'
template_file = ENV['TEMPLATE'] || 'test.txt'
template = File.read(template_file)

CSV.foreach(csv_file, :headers => :first_row) do |row|
  begin
    msg = Msg.new(row, template)
    Email.new(msg).dispatch
  rescue StandardError => e
    puts "Failed to send to %s - %s." % [msg.email, e]
  else
    puts "Sent to %s." % msg.email
  end
end
