#!/usr/bin/env ruby

require 'csv'
require 'dotenv'
require 'pony'
require_relative 'lib/msg'
require_relative 'lib/email'

Dotenv.load

csv_file = ENV['CSV'] || 'test.csv'
template_file = ENV['TEMPLATE'] || 'test.txt'
template = File.read(template_file)

CSV.foreach(csv_file, :headers => :first_row) do |row|
  msg = Msg.new(row, template)
  begin
    Email.new(msg).dispatch
  rescue StandardError
    puts "Failed to send to %s" % msg.email
  else
    puts "Sent to %s" % msg.email
  end
end
